INSERT INTO PRODUCTS(UPC, MFGR, MODEL, PROD_NAME, UNIT_LIST_PRICE, UNITS_IN_STOCK) VALUES ('2345678', 'Hasbro', '1', 'Toy Car', 10.99, 34)

INSERT INTO PRODUCTS(UPC, MFGR, MODEL, PROD_NAME, UNIT_LIST_PRICE, UNITS_IN_STOCK) VALUES ('98763', 'Lego', '14', 'Space Ship', 25.99, 32)

INSERT INTO PRODUCTS(UPC, MFGR, MODEL, PROD_NAME, UNIT_LIST_PRICE, UNITS_IN_STOCK) VALUES ('35753', 'Nintendo', '2', 'Nintendo OLED Switch', 500.99, 7)

INSERT INTO PRODUCTS(UPC, MFGR, MODEL, PROD_NAME, UNIT_LIST_PRICE, UNITS_IN_STOCK) VALUES ('84563', 'Nature', '3', 'Pine Tree', 25.99, 9995)

INSERT INTO PRODUCTS(UPC, MFGR, MODEL, PROD_NAME, UNIT_LIST_PRICE, UNITS_IN_STOCK) VALUES ('458567', 'Nature', '1', 'Rock', 2.99, 29995)
